backend:
  name: github
  repo: anthonyricse98/comerce-web
  branch: main
  base_url: https://api.netlify.com
  
media_folder: "public/images/uploads" 
public_folder: "/comerce-web/images/uploads"

collections:
  - name: "locales"
    label: "Navegación"
    delete: false
    create: false
    files:
      - name: "es"
        label: "Logo"
        file: "locales/es/dashboard-navigation.json"
        fields:
          - { label: "COMERCEWEB-DASHBOARD-LOGO", name: "COMERCEWEB-DASHBOARD-LOGO", widget: "string" }