name: Despliegue Automático al hacer Push

on:
  push:
    branches:
      - main  # Escucha cambios en main (CMS o pushes locales)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      # Combinamos el build y el deploy usando directamente tus comandos de npm
      - name: Ejecutar Despliegue Oficial
        run: npm run deploy
        env:
          # Le damos permisos al comando para que pueda escribir en tu repositorio de GitHub de forma segura
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}